site_name: eBGF
nav:
    - Home: index.md
    - Contact:
        - FAQ: faq.md
        - Contribution: contribute.md
        - Presskit: press.md
    - Glossar: glossar.md
    - RFCs:
        - Institutional: 
            - Institutional introduction: RFC/1-inst.md
            - RFC-1001: RFC/1-inst/RFC-1001.md
            - RFC-1002: RFC/1-inst/RFC-1002.md
        - Economics: 
            - Economics introduction: RFC/2-eco.md
            - RFC-2001: RFC/2-eco/RFC-2001.md
            - RFC-2002: RFC/2-eco/RFC-2002.md
        - Legal: 
            - Legal introduction: RFC/3-legal.md
            - RFC-3001:  RFC/3-legal/RFC-3001.md
            - RFC-3002:  RFC/3-legal/RFC-3002.md
        - Technical: 
            - Technical introduction: RFC/4-tech.md
            - RFC-4001: RFC/4-tech/RFC-4001.md
            - RFC-4002: RFC/4-tech/RFC-4002.md
    - Privacy: privacy.md
    - Imprint: imprint.md
theme:
  name: material
